#!/usr/bin/env python3
"""Create licensed Noto SC subset and deterministic uncompressed LVGL font.
Requires fonttools and Pillow/FreeType (see assets/README.md).
"""
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from fontTools.ttLib import TTFont
from fontTools import subset
ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets/fonts'
source = Path(sys.argv[1]) if len(sys.argv) > 1 else OUT / 'NotoSansCJKsc-Cast.otf'
converter = ROOT / 'build/cast-font-tools/node_modules/lv_font_conv/lv_font_conv.js'
text = (OUT / 'cast-glyphs.txt').read_text().rstrip('\n')
font = TTFont(source, fontNumber=2) if source.suffix == '.ttc' else TTFont(source)
missing = set(map(ord, text)) - set(font.getBestCmap())
assert not missing, f'Missing source glyphs: {missing}'
if source.resolve() != (OUT / 'NotoSansCJKsc-Cast.otf').resolve():
    sub = subset.Subsetter(); sub.populate(text=text); sub.subset(font)
    font.save(OUT / 'NotoSansCJKsc-Cast.otf')
# Native FreeType avoids Node/WASM, unavailable in the iOS JIT-less runtime.
from PIL import ImageFont, __version__ as pillow_version, features
raster = ImageFont.truetype(str(OUT / 'NotoSansCJKsc-Cast.otf'), 16)
bitmap = []; descriptors = ['    {0},']; cps = sorted(map(ord, text))
for cp in cps:
    ch = chr(cp)
    mask, offset = raster.getmask2(ch, mode='L', anchor='ls')
    w, h = mask.size
    pixels = list(mask)
    quantized = [(p * 15 + 127) // 255 for p in pixels]
    packed = [(quantized[i] << 4) | (quantized[i+1] if i+1 < len(quantized) else 0)
              for i in range(0, len(quantized), 2)]
    descriptors.append('    {.bitmap_index=%d, .adv_w=%d, .box_w=%d, .box_h=%d, .ofs_x=%d, .ofs_y=%d},' %
        (len(bitmap), round(raster.getlength(ch)*16), w, h, offset[0], -offset[1]-h))
    bitmap.extend(packed)
lines = ['/* Generated by tools/generate_cast_font.py; Noto Sans CJK SC, OFL.txt. */',
 '#include "lvgl.h"', 'static const uint8_t glyph_bitmap[] = {']
lines += ['    '+','.join('0x%02x'%v for v in bitmap[i:i+20])+',' for i in range(0,len(bitmap),20)]
lines += ['};','static const lv_font_fmt_txt_glyph_dsc_t glyph_dsc[] = {'] + descriptors + ['};',
 'static const uint16_t unicode_list[] = {', ','.join(str(cp-32) for cp in cps), '};',
 'static const lv_font_fmt_txt_cmap_t cmaps[] = {{',
 ' .range_start=32, .range_length=%d, .glyph_id_start=1,' % (cps[-1]-31),
 ' .unicode_list=unicode_list, .glyph_id_ofs_list=NULL, .list_length=%d,' % len(cps),
 ' .type=LV_FONT_FMT_TXT_CMAP_SPARSE_TINY }};',
 'static const lv_font_fmt_txt_dsc_t font_dsc = {',
 ' .glyph_bitmap=glyph_bitmap, .glyph_dsc=glyph_dsc, .cmaps=cmaps,',
 ' .kern_dsc=NULL, .kern_scale=0, .cmap_num=1, .bpp=4, .kern_classes=0, .bitmap_format=0 };',
 'const lv_font_t cast_font_16 = {',
 ' .get_glyph_dsc=lv_font_get_glyph_dsc_fmt_txt, .get_glyph_bitmap=lv_font_get_bitmap_fmt_txt,',
 ' .line_height=24, .base_line=5, .subpx=LV_FONT_SUBPX_NONE,',
 ' .underline_position=-2, .underline_thickness=1, .dsc=&font_dsc };']
(OUT/'cast_font_16.c').write_text('\n'.join(lines)+'\n', newline='\n')
paths = ['NotoSansCJKsc-Cast.otf', 'cast_font_16.c', 'cast-glyphs.txt']
manifest = {'family':'Noto Sans CJK SC Regular', 'converter':'Pillow '+pillow_version+' / FreeType '+features.version_module('freetype2'),
 'size':16, 'bpp':4, 'compressed':False, 'codepoints':sorted(map(ord,text)),
 'sha256':{p:hashlib.sha256((OUT/p).read_bytes()).hexdigest() for p in paths}}
(OUT/'cast-font-manifest.json').write_text(json.dumps(manifest,indent=2)+'\n', newline='\n')
