#!/usr/bin/env python3
"""Deterministic v4-only snapshot -> flash-resident tables + complete glyph inventory."""
import hashlib, json, re
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / 'main/cast_source'
UI = ['大连','历史场','历史名单','未发布','离线','最新','在线更新','长按确定更新','日期未设置','立即检查更新','正在同步','同步失败','尚未配置服务','未连接网络','校验失败','保存失败','已存本机','演出阵容','选择日期','上下调整日期','名单日期','发布时段','无自动轮询','资料待补充','阵容历史资料','返回城市','检查更新','仅供历史参考','组','位','已验证更新','协议不支持','不支持的文字','演员手册','选择城市','选择场次','演员名单','阵容待更新','该城市名单尚未提供','作品与角色','个人作品与经历待补充','资料说明','仅为历史资料，非当日节目承诺','上/下选择 确定进入','上/下翻页 长按返回','长按确定返回','电量未知','按键初始化失败','离线快照','今日场','下午场']
def load():
    data = json.loads((SRC/'data.json').read_text(encoding='utf-8'))
    seed = re.search(r'<script[^>]*id="seed"[^>]*>(.*?)</script>', (SRC/'index.html').read_text(encoding='utf-8'), re.S)
    assert seed and json.loads(seed[1]) == data, 'v4 HTML seed differs from data.json'
    assert [v['id'] for v in data['venues']] == ['zhongjie','haerbin','beijing','changchun','nanjing','taian-afternoon','taian','linyi']
    assert [len(v['cards']) for v in data['venues']] == [5,5,5,5,0,3,5,0]
    return data

def pages(text):
    # Thirteen 16px Han advances fit the 216px reader.
    lines = []
    for line in text.split('\n'):
        lines.extend([line[i:i+13] for i in range(0,len(line),13)] or [''])
    return ['\n'.join(lines[i:i+7]) for i in range(0,len(lines),7)]

def generate():
    d=load(); out=['/* Generated by tools/generate_cast.py; do not edit. */','#include "cast_data.h"']; glyphs=''.join(UI)+''.join(chr(i) for i in range(32,127))+d['date']
    def q(s): return json.dumps(s,ensure_ascii=False)
    cities=[]; venues=[]; actors=[]
    for vi,v in enumerate(d['venues']):
        city=v['title'].replace('大舞台','')
        if city not in cities: cities.append(city)
        glyphs+=v['title']+v['session']+city
        first=len(actors)
        for ai,a in enumerate(v['cards']):
            key=f'cast_pages_{vi}_{ai}'; chunks=[]
            sections=[('作品与角色',a['credits'])] if a['credits'] else []
            # Stage-feature sections are retired; preserve the archived source only.
            if not sections: sections=[('资料说明','个人作品与经历待补充')]
            sections += [('资料说明',a['notes'])]
            for title,text in sections:
                glyphs+=title+text
                chunks += [(title,p) for p in pages(text)]
            glyphs+=a['names']
            out += [f'static const cast_page_t {key}[] = {{']+[f'    {{{q(t)}, {q(p)}}},' for t,p in chunks]+['};']
            actors.append(f'    {{{q(a["names"])}, {key}, {len(chunks)}}},')
        venues.append(f'    {{{q(v["title"])}, {q(v["session"])}, {cities.index(city)}, {first}, {len(v["cards"])}}},')
    venues.append('    {"大连大舞台", "", 7, 28, 0},')
    cities.append('大连')
    out+=['const cast_actor_t cast_actors[] = {']+actors+['};','const cast_venue_t cast_venues[9] = {']+venues+['};','const char *const cast_cities[8] = {',', '.join(q(c) for c in cities),'};',f'const char cast_date[] = {q(d["date"])};']
    glyphs += ''.join((ROOT/'main/main.c').read_text(encoding='utf-8')) + '晚场午场'
    # GB2312 common Han characters plus the exact historical/UI repertoire.
    # The source font and server export are verified against this inventory.
    for cp in range(0x4e00,0xa000):
        try: chr(cp).encode('gb2312')
        except UnicodeEncodeError: continue
        glyphs += chr(cp)
    glyphs += (ROOT/'assets/fonts/catalog-characters.txt').read_text(encoding='utf8')
    inventory=''.join(sorted(set(c for c in glyphs if ord(c)>=32)))
    hashes={n:hashlib.sha256((SRC/n).read_bytes()).hexdigest() for n in ['data.json','index.html']}
    manifest={'source':'/var/minis/shared/cuecards-v4','source_date':d['date'],'sha256':hashes,'cities':7,'venues':8,'actors':len(actors),'glyph_count':len(inventory)}
    return {'main/cast_data.c':'\n'.join(out)+'\n','assets/fonts/cast-glyphs.txt':inventory+'\n','main/cast_source/manifest.json':json.dumps(manifest,ensure_ascii=False,indent=2)+'\n'}
if __name__=='__main__':
    import sys
    for path,text in generate().items():
        dest=ROOT/path
        if '--check' in sys.argv: assert dest.read_text(encoding='utf-8')==text, f'stale: {path}'
        else: dest.write_text(text, encoding='utf-8', newline='\n')
